name: Deploy to Netlify

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Lint & Typecheck
        run: |
          npm run lint
          npm run typecheck

      - name: Build
        run: npm run build

      - name: Deploy to Netlify
        uses: netlify/actions/cli@v5
        with:
          args: deploy --dir=dist --prod --message "CI deploy ${{ github.sha }}"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
